version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1253
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/sps_db
      - spring.datasource.username=root
      - spring.datasource.password=1253
      - spring.profiles.active=dev
      - server.port=8080
      - aws.region=${AWS_REGION}
      - aws.accessKey=${AWS_ACCESS_KEY}
      - aws.secret=${AWS_SECRET}
      - aws.violationBucket=${AWS_S3_BUCKET}
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge

