name: test
on: 
   push:


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get the current date for tagging Docker image
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M%S')"

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.SPS_IMAGE }}:${{ steps.date.outputs.date }}
    outputs:
         date: ${{ steps.date.outputs.date }}
   
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker rm $(docker ps -a -q)
          docker pull  ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.SPS_IMAGE }}:${{ needs.build.outputs.date }}
          docker run --env=spring.profiles.active=prod --env=aws.region=${{ secrets.AWS_REGION }} --env=aws.accessKey=${{ secrets.AWS_ACCESS_KEY }} --env=aws.secret=${{ secrets.AWS_SECRET }} --env=aws.violationBucket=${{ secrets.AWS_S3_BUCKET }}  -p 80:80 -d --name sps  ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.SPS_IMAGE }}:${{ needs.build.outputs.date }}
        

